/**
 * ===================================
 * SERVICE WORKER - PWA OFFLINE SUPPORT
 * Enterprise-Grade Caching Strategy
 * =================================== */

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { cacheNames, setCatchHandler } from 'workbox-core';

// ===================================
// CACHE CONFIGURATION
// ===================================

const CACHE_VERSION = 'v1';
const STATIC_CACHE = `static-${CACHE_VERSION}`;
const DYNAMIC_CACHE = `dynamic-${CACHE_VERSION}`;
const IMAGE_CACHE = `images-${CACHE_VERSION}`;
const API_CACHE = `api-${CACHE_VERSION}`;
const OFFLINE_PAGE = '/offline.html';

// ===================================
// PRECACHE ASSETS
// ===================================

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST || []);

// Cleanup old caches on activate
cleanupOutdatedCaches();

// ===================================
// CACHING STRATEGIES
// ===================================

/**
 * Images: Cache First with expiration
 * - Try cache first
 * - Fall back to network
 * - Expire after 30 days or 100 images
 */
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: IMAGE_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
        purgeOnQuotaError: true
      })
    ]
  })
);

/**
 * API Requests: Network First with timeout
 * - Try network first
 * - Timeout after 3 seconds
 * - Fall back to cache
 * - Update cache in background
 */
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: API_CACHE,
    networkTimeoutSeconds: 3,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
        purgeOnQuotaError: true
      })
    ]
  })
);

/**
 * Google Fonts: Cache First
 */
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || 
               url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60 // 1 year
      })
    ]
  })
);

/**
 * Static Assets (JS, CSS): Stale While Revalidate
 * - Serve from cache immediately
 * - Update cache in background
 * - Fast and always fresh
 */
registerRoute(
  ({ request }) => 
    request.destination === 'script' || 
    request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: STATIC_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 7 * 24 * 60 * 60 // 7 days
      })
    ]
  })
);

/**
 * Navigation Requests: Network First for HTML pages
 * - Try network first
 * - Fall back to cached offline page if offline
 */
const navigationHandler = new NetworkFirst({
  cacheName: DYNAMIC_CACHE,
  networkTimeoutSeconds: 3,
  fallbackURL: OFFLINE_PAGE,
  plugins: [
    new ExpirationPlugin({
      maxEntries: 50,
      maxAgeSeconds: 24 * 60 * 60 // 24 hours
    })
  ]
});

registerRoute(new NavigationRoute(navigationHandler));

// ===================================
// BACKGROUND SYNC FOR OFFLINE ACTIONS
// ===================================

const bgSyncPlugin = new BackgroundSyncPlugin('queue', {
  maxRetentionTime: 24 * 60 // Retry for up to 24 hours
});

// Queue failed POST/PUT/DELETE requests
registerRoute(
  ({ url, request }) => 
    url.pathname.startsWith('/api/') && 
    ['POST', 'PUT', 'DELETE'].includes(request.method),
  new NetworkFirst({
    cacheName: API_CACHE,
    plugins: [bgSyncPlugin]
  }),
  'POST'
);

// ===================================
// CUSTOM FETCH HANDLER WITH FALLBACKS
// ===================================

setCatchHandler(async ({ event }) => {
  switch (event.request.destination) {
    case 'document':
      // Return offline page for navigation requests
      return caches.match(OFFLINE_PAGE);
    
    case 'image':
      // Return placeholder image for failed image requests
      return caches.match('/images/icons/icon-512x512.png');
    
    default:
      // Return error response
      return Response.error();
  }
});

// ===================================
// SERVICE WORKER LIFECYCLE EVENTS
// ===================================

/**
 * Install Event
 * - Cache critical assets
 */
self.addEventListener('install', (event) => {
  console.log('[ServiceWorker] Installing...');
  
  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) => {
      return cache.addAll([
        OFFLINE_PAGE,
        '/',
        '/manifest.json',
        '/images/icons/icon-512x512.png'
      ]);
    })
  );
  
  // Force activation
  self.skipWaiting();
});

/**
 * Activate Event
 * - Clean up old caches
 * - Claim clients
 */
self.addEventListener('activate', (event) => {
  console.log('[ServiceWorker] Activating...');
  
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => {
            // Delete old cache versions
            return name.startsWith('static-') || 
                   name.startsWith('dynamic-') || 
                   name.startsWith('images-') ||
                   name.startsWith('api-');
          })
          .filter((name) => {
            // Keep current version
            return name !== STATIC_CACHE && 
                   name !== DYNAMIC_CACHE && 
                   name !== IMAGE_CACHE &&
                   name !== API_CACHE;
          })
          .map((name) => {
            console.log('[ServiceWorker] Deleting old cache:', name);
            return caches.delete(name);
          })
      );
    }).then(() => {
      // Take control of all clients
      return self.clients.claim();
    })
  );
});

// ===================================
// MESSAGE HANDLING
// ===================================

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  
  if (event.data && event.data.type === 'CLEAR_CACHE') {
    event.waitUntil(
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames.map((name) => caches.delete(name))
        );
      }).then(() => {
        event.ports[0].postMessage({ type: 'CACHE_CLEARED' });
      })
    );
  }
  
  if (event.data && event.data.type === 'GET_CACHE_STATUS') {
    event.waitUntil(
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames.map(async (name) => {
            const cache = await caches.open(name);
            const keys = await cache.keys();
            return { name, size: keys.length };
          })
        );
      }).then((status) => {
        event.ports[0].postMessage({ 
          type: 'CACHE_STATUS', 
          data: status 
        });
      })
    );
  }
});

// ===================================
// PUSH NOTIFICATIONS
// ===================================

self.addEventListener('push', (event) => {
  const data = event.data?.json() || {};
  
  const options = {
    body: data.body || 'New notification from Fashion Marketplace',
    icon: '/images/icons/icon-192x192.png',
    badge: '/images/icons/badge-72x72.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/',
      productId: data.productId,
      orderId: data.orderId
    },
    actions: [
      {
        action: 'open',
        title: 'Open',
        icon: '/images/icons/action-open.png'
      },
      {
        action: 'dismiss',
        title: 'Dismiss',
        icon: '/images/icons/action-dismiss.png'
      }
    ],
    tag: data.tag || 'fashion-marketplace-notification',
    requireInteraction: true,
    silent: false
  };
  
  event.waitUntil(
    self.registration.showNotification(data.title || 'Fashion Marketplace', options)
  );
});

// ===================================
// NOTIFICATION CLICK HANDLER
// ===================================

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  if (event.action === 'dismiss') {
    return;
  }
  
  const urlToOpen = event.notification.data?.url || '/';
  
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients) => {
        // Check if there's already a window open with this URL
        for (let client of windowClients) {
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus();
          }
        }
        
        // Open new window if no existing one found
        if (clients.openWindow) {
          return clients.openWindow(urlToOpen);
        }
      })
  );
});

// ===================================
// PERIODIC BACKGROUND SYNC
// ===================================

self.addEventListener('periodicsync', (event) => {
  if (event.tag === 'sync-cart') {
    event.waitUntil(syncCart());
  }
  
  if (event.tag === 'update-prices') {
    event.waitUntil(updatePrices());
  }
});

async function syncCart() {
  // Sync cart with server in background
  try {
    const response = await fetch('/api/v1/cart/sync', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' }
    });
    
    if (!response.ok) throw new Error('Sync failed');
    
    console.log('[ServiceWorker] Cart synced successfully');
  } catch (error) {
    console.warn('[ServiceWorker] Cart sync failed:', error);
  }
}

async function updatePrices() {
  // Update product prices in cache
  try {
    const response = await fetch('/api/v1/products/prices/check');
    
    if (!response.ok) throw new Error('Price check failed');
    
    const priceUpdates = await response.json();
    
    if (priceUpdates.updated > 0) {
      // Notify user about price changes
      self.registration.showNotification('Price Updates Available', {
        body: `${priceUpdates.updated} items in your wishlist have new prices`,
        icon: '/images/icons/icon-192x192.png',
        data: { url: '/account/wishlist' }
      });
    }
  } catch (error) {
    console.warn('[ServiceWorker] Price update check failed:', error);
  }
}

// ===================================
// LOGGING & DEBUGGING
// ===================================

console.log('[ServiceWorker] Service Worker loaded');
console.log('[ServiceWorker] Cache Version:', CACHE_VERSION);
